APPNAME=sxge
CXX ?= g++
SXGE_TOPDIR=$(shell pwd)/../../
DEFINES += -I$(SXGE_TOPDIR)/libsxge
WOPTS=-Wall -Wextra -Wpedantic
CXFLAGS=-std=c++0x -O0 -pg $(DEFINES) $(WOPTS)

CXFILES = main.cc
OBJFILES = $(patsubst %.cc,%.o,$(CXFILES))

all: $(APPNAME)

$(APPNAME): $(OBJFILES)
	$(CXX) $(CXFLAGS) $(LIBS) $(DEFINES) -o $@ $(OBJFILES)

$(OBJFILES): %.o: %.cc
	$(CXX) $(CXFLAGS) $(LIBS) $(DEFINES) -c $< -o $@

clean:
	rm -f $(APPNAME)
	rm -f *.o
	rm -f gmon.out
